<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.7.0" />
    <ProjectReference Include="..\Generated\PlanningPoker.Generated.csproj" />
  </ItemGroup>

</Project>
